### ISSUE TITLE
Consider adding a LICENSE to the repository

### ISSUE THREAD

**Issue by mdccUVa** [uva-trasgo/UVaFTLE#4]
I know UVaFTLE is supposed to be open-source and free to use, to contribute to open science (as specified in the paper). Nevertheless, no license for the software is specified. This is actually a problem, as specified by GitHub's Terms of Service:

> If you find software that **doesn’t have a license**, that generally means **you have no permission from the creators of the software to use, modify, or share the software**. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Thus, it is strongly suggested to always add a license. Further reading: [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

GitHub provides the [choosealicense.com](choosealicense.com) website to help developers choose a license for their software that suits their purpose. From inside the repository's page, it is as easy as clicking a few buttons, and GitHub will automatically add a `LICENSE` file to the root of the repository with the chosen license. It will also be displayed on the right side of the repository's page, in the "About" section.

Some options I considered are:
- Creative Commons Zero v1.0 Universal License (cc0-1.0); or another Creative Commons license. This is the license usually chosen by Arturo when releasing any software published in an article. And he knows more than I do about that.
- MIT License. A very popular license for open software in which the author doesn't really care what people use their code for. It basically says "you can do anything, as long as my code retains this license".
- GNU GPLv3, or another GPL license. A license that tries to keep open software open no matter the modifications made to it. It is the license of choice for some software published in scientific articles; [for example this one](https://github.com/vtsynergy/OpenDwarfs).

**If a license is chosen and it is communicated to me, I can make the corresponding changes myself.**

**Comment by rociocarratalasaez** [comment]
Solved, thanks!
