### ISSUE TITLE
Makefile clean recipe is wrong

### ISSUE THREAD

**Issue by mdccUVa** [uva-trasgo/UVaFTLE#6]
Both [CPU](https://github.com/uva-trasgo/UVaFTLE/blob/master/CPU/Makefile#L30) and [CUDA](https://github.com/uva-trasgo/UVaFTLE/blob/master/CUDA/Makefile#L30) Makefiles (and the new Makefiles in the `sycl-implementation` branch of Pull Request #5) have the following recipe for `clean`:
```bash
cd ${DIR_bin} && rm ${OBJS} && cd ..
```
Nevertheless, the variable `OBJS` is never setted, and executing this recipe fails with message `rm: missing operand`.

I open an issue instead of a Pull Request because I cannot test right now if this is really an issue or something I'm missing, as the platform I am currently working on doesn't have `nvcc` so I cannot compile the sources.

**Comment by rociocarratalasaez** [comment]
The Makefiles have been updated. Thanks for your contribution!
Please notify any issue you may find.
